/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_hesoft_lame_Native */

#ifndef _Included_io_github_hesoft_lame_Native
#define _Included_io_github_hesoft_lame_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_hesoft_lame_Native
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_github_hesoft_lame_Native_getVersion
        (JNIEnv *, jclass);

/*
 * Class:     io_github_hesoft_lame_Native
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_github_hesoft_lame_Native_create
        (JNIEnv *, jclass);

/*
 * Class:     io_github_hesoft_lame_Native
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_github_hesoft_lame_Native_close
        (JNIEnv *, jclass, jlong);

/*
 * Class:     io_github_hesoft_lame_Native
 * Method:    init_params
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_io_github_hesoft_lame_Native_init_1params
        (JNIEnv *, jclass, jlong);

/*
 * Class:     io_github_hesoft_lame_Native
 * Method:    set_input
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_io_github_hesoft_lame_Native_set_1input
        (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     io_github_hesoft_lame_Native
 * Method:    set_output
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_io_github_hesoft_lame_Native_set_1output
        (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     io_github_hesoft_lame_Native
 * Method:    encodeByte
 * Signature: (J[B[BI[B)I
 */
JNIEXPORT jint JNICALL Java_io_github_hesoft_lame_Native_encodeByte
        (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray, jint, jbyteArray);

/*
 * Class:     io_github_hesoft_lame_Native
 * Method:    encode
 * Signature: (J[B[BI[B)I
 */
JNIEXPORT jint JNICALL Java_io_github_hesoft_lame_Native_encode
        (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray, jint, jbyteArray);

/*
 * Class:     io_github_hesoft_lame_Native
 * Method:    encodeInt
 * Signature: (J[B[BI[B)I
 */
JNIEXPORT jint JNICALL Java_io_github_hesoft_lame_Native_encodeInt
        (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray, jint, jbyteArray);

/*
 * Class:     io_github_hesoft_lame_Native
 * Method:    encodeFloat
 * Signature: (J[B[BI[B)I
 */
JNIEXPORT jint JNICALL Java_io_github_hesoft_lame_Native_encodeFloat
        (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray, jint, jbyteArray);

/*
 * Class:     io_github_hesoft_lame_Native
 * Method:    encodeDouble
 * Signature: (J[B[BI[B)I
 */
JNIEXPORT jint JNICALL Java_io_github_hesoft_lame_Native_encodeDouble
        (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray, jint, jbyteArray);

/*
 * Class:     io_github_hesoft_lame_Native
 * Method:    encodeInterleavedByte
 * Signature: (J[BI[B)I
 */
JNIEXPORT jint JNICALL Java_io_github_hesoft_lame_Native_encodeInterleavedByte
        (JNIEnv *, jclass, jlong, jbyteArray, jint, jbyteArray);

/*
 * Class:     io_github_hesoft_lame_Native
 * Method:    encodeInterleaved
 * Signature: (J[BI[B)I
 */
JNIEXPORT jint JNICALL Java_io_github_hesoft_lame_Native_encodeInterleaved
        (JNIEnv *, jclass, jlong, jbyteArray, jint, jbyteArray);

/*
 * Class:     io_github_hesoft_lame_Native
 * Method:    encodeInterleavedInt
 * Signature: (J[BI[B)I
 */
JNIEXPORT jint JNICALL Java_io_github_hesoft_lame_Native_encodeInterleavedInt
        (JNIEnv *, jclass, jlong, jbyteArray, jint, jbyteArray);

/*
 * Class:     io_github_hesoft_lame_Native
 * Method:    encodeInterleavedFloat
 * Signature: (J[BI[B)I
 */
JNIEXPORT jint JNICALL Java_io_github_hesoft_lame_Native_encodeInterleavedFloat
        (JNIEnv *, jclass, jlong, jbyteArray, jint, jbyteArray);

/*
 * Class:     io_github_hesoft_lame_Native
 * Method:    encodeInterleavedDouble
 * Signature: (J[BI[B)I
 */
JNIEXPORT jint JNICALL Java_io_github_hesoft_lame_Native_encodeInterleavedDouble
        (JNIEnv *, jclass, jlong, jbyteArray, jint, jbyteArray);

/*
 * Class:     io_github_hesoft_lame_Native
 * Method:    flush
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_io_github_hesoft_lame_Native_flush
        (JNIEnv *, jclass, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
